### ISSUE TITLE
The class sister/sister/utils/manager.py / need to be updated.

### ISSUE THREAD

**Issue by FRUNIROMA1** [EnSpec/sister#14]
Hello , thanks a lot for sharing this great codebase! 
In this function: https://github.com/EnSpec/sister/blob/44d225867feed5079151c68bcdaf9602793eaf9c/sister/utils/manager.py#L80 there is **res** as an imput argument : https://github.com/EnSpec/sister/blob/44d225867feed5079151c68bcdaf9602793eaf9c/sister/sensors/prisma.py#L42  but dons't require that argument anymore. 

Also the base_name parameter of the class https://github.com/EnSpec/sister/blob/44d225867feed5079151c68bcdaf9602793eaf9c/sister/utils/manager.py#L33
is producing name  of directories with the same string repeated.
Thanks

**Comment by adamchlus** [comment]
Thanks for bringing this to my attention. The `manager` submodule has been deprecated and is no longer supported, I have removed it from the codebase.
